name: "laracasts-php-for-beginners"

services:
  db:
    container_name: laracasts-mysql
    image: mariadb
    ports:
      - "3310:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        TZ: "America/Mexico_City"
    volumes:
      - laracasts:/var/lib/mysql
volumes:
  laracasts:
